version: '3.9'

services:
  web:
    image: alpeza/habmaps_web:latest
    container_name: habmaps_web
    environment:
      REACT_APP_API_GRAPHQL_URL: http://habmaps_strapi:1337/graphql
      REACT_APP_API_URL: http://habmaps_strapi:1337
    ports:
      - "8991:80"
    networks:
      - core_npm_hcinet

networks:
  core_npm_hcinet:
    external: true
